package com.pokemon.tcg.domain.model.game;

public enum GameEventType {
    GAME_STARTED,
    TURN_STARTED,
    CARD_DRAWN,
    POKEMON_PLACED,
    ENERGY_ATTACHED,
    TRAINER_PLAYED,
    POKEMON_EVOLVED,
    POKEMON_RETREATED,
    ABILITY_USED,
    ATTACK_DECLARED,
    DAMAGE_APPLIED,
    SPECIAL_CONDITION_APPLIED,
    SPECIAL_CONDITION_CLEARED,
    POKEMON_KNOCKED_OUT,
    PRIZE_TAKEN,
    TURN_ENDED,
    GAME_OVER,
    SUDDEN_DEATH_STARTED,
    MULLIGAN_DECLARED,
    RECONNECTED
}
